### ISSUE TITLE
Error after the recent update in classic era

### ISSUE THREAD

**Issue by YEnthalpy** [tkyeung357/MerInspect-classic-era#4]
Hi tkyeung, there is an error occurring after the latest update. I think it was caused by Blizzard deprecating some old APIs.

Here is the error message. Could you please look into it? Thanks!

MerInspect-classic-era/Options.lua:226: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "@MerInspect-classic-era/Options.lua"]:226: in main chunk

Locals:
LibEvent = <table> {
 triggers = <table> {
 }
 events = <table> {
 }
}
VERSION = 1
addon = "MerInspect-classic-era"
ns = <table> {
}
L = <table> {
}
DefaultDB = <table> {
 ShowOwnFrameWhenInspecting = false
 Debug = false
 ShowCharacterItemStats = true
 ShowInspectAngularBorder = false
 ShowCharacterItemSheet = true
 ShowItemStats = true
 ShowInspectItemSheet = true
 version = 1
 position = <table> {
 }
 DefaultPosition = false
 ShowItemSlotString = true
 ShowInspectColoredLabel = true
 ShowItemBorder = true
}
options = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
}
frame = Frame {
 title = FontString {
 }
 name = "MerInspect-classic-era"
}
(*temporary) = nil
(*temporary) = Frame {
 title = FontString {
 }
 name = "MerInspect-classic-era"
}
(*temporary) = "attempt to call global 'InterfaceOptions_AddCategory' (a nil value)"

**Comment by tkyeung357** [comment]
thanks for the report; I will find time to look into it! Sent from my iPhoneOn Oct 4, 2024, at 19:07, Zehan Yang ***@***.***> wrote:﻿
Hi tkyeung, there is an error occurring after the latest update. I think it was caused by Blizzard deprecating some old APIs.
Here is the error message. Could you please look into it? Thanks!
MerInspect-classic-era/Options.lua:226: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string ***@***.***/Options.lua"]:226: in main chunk
Locals:
LibEvent =  {
triggers =  {
}
events =  {
}
}
VERSION = 1
addon = "MerInspect-classic-era"
ns =  {
}
L =  {
}
DefaultDB =  {
ShowOwnFrameWhenInspecting = false
Debug = false
ShowCharacterItemStats = true
ShowInspectAngularBorder = false
ShowCharacterItemSheet = true
ShowItemStats = true
ShowInspectItemSheet = true
version = 1
position =  {
}
DefaultPosition = false
ShowItemSlotString = true
ShowInspectColoredLabel = true
ShowItemBorder = true
}
options =  {
1 =  {
}
2 =  {
}
3 =  {
}
4 =  {
}
5 =  {
}
6 =  {
}
7 =  {
}
8 =  {
}
}
frame = Frame {
title = FontString {
}
name = "MerInspect-classic-era"
}
(*temporary) = nil
(*temporary) = Frame {
title = FontString {
}
name = "MerInspect-classic-era"
}
(*temporary) = "attempt to call global 'InterfaceOptions_AddCategory' (a nil value)"

**Comment by tkyeung357** [comment]
Hi @YEnthalpy  the Issue has been addressed, and I submitted a new version (v1.1.4) to Curseforge.

**Comment by YEnthalpy** [comment]
Thanks very much :)
